# Generated by Django 3.1.2 on 2020-10-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_remove_table_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
