# Generated by Django 3.1.2 on 2020-10-19 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0003_delete_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=20)),
                ('sex', models.IntegerField(choices=[(1, 'м'), (2, 'ж')])),
                ('position', models.CharField(max_length=20)),
                ('is_su', models.BooleanField()),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path', models.ImageField(upload_to='media/')),
                ('well', models.CharField(max_length=20)),
                ('depth', models.IntegerField()),
                ('kind', models.IntegerField(choices=[(1, 'daylight'), (2, 'ultraviolet')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField()),
                ('name', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_path', models.FilePathField()),
                ('path', models.FilePathField()),
                ('mask_id', models.ManyToManyField(db_table='Model_to_mask', to='Main.Model')),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.photo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.user')),
            ],
        ),
    ]
