# Generated by Django 3.1.2 on 2020-10-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_mask_model_photo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mask',
            old_name='mask_id',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='mask',
            old_name='photo_id',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='mask',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='user_id',
            new_name='user',
        ),
    ]
