# Generated by Django 3.1.2 on 2020-10-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20201019_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='likes',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
