# Generated by Django 3.1.2 on 2020-10-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_mask_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='well',
            field=models.CharField(max_length=50),
        ),
    ]
