# Generated by Django 3.1.2 on 2020-10-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20201024_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='classification_path',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='mask',
            name='path',
            field=models.FileField(upload_to='media/'),
        ),
    ]
