# Generated by Django 3.1.2 on 2020-10-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20201028_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
