# Generated by Django 3.1.2 on 2020-11-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_auto_20201029_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mask',
            name='classification_path',
        ),
        migrations.RemoveField(
            model_name='mask',
            name='path',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_path',
        ),
        migrations.AddField(
            model_name='mask',
            name='classification',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mask',
            name='mask',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mask',
            name='users_who_like',
            field=models.ManyToManyField(db_table='Likes', related_name='likes', to='Main.User'),
        ),
        migrations.AddField(
            model_name='model',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
