# Generated by Django 3.1.2 on 2020-11-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20201103_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
