# Generated by Django 3.1.2 on 2020-11-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_auto_20201103_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='classification',
            field=models.TextField(),
        ),
    ]
