# Generated by Django 3.1.2 on 2020-11-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_auto_20201104_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='kind',
            field=models.IntegerField(choices=[(1, 'daylight'), (2, 'ultraviolet')], default=1),
            preserve_default=False,
        ),
    ]
