# Generated by Django 3.1.2 on 2020-11-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_model_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='mask',
            field=models.BinaryField(),
        ),
    ]
