# Generated by Django 3.1.2 on 2020-11-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_auto_20201111_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='model',
            field=models.ManyToManyField(blank=True, db_table='Model_to_mask', to='Main.Model'),
        ),
        migrations.AlterField(
            model_name='mask',
            name='users_who_like',
            field=models.ManyToManyField(blank=True, db_table='Likes', related_name='likes', to='Main.User'),
        ),
    ]
