# Generated by Django 3.1.2 on 2020-11-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_auto_20201112_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='model',
            field=models.BinaryField(default=bytes()),
            preserve_default=False,
        ),
    ]
