# Generated by Django 3.1.2 on 2020-11-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_model_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mask',
            name='model',
        ),
    ]
