# Generated by Django 3.1.2 on 2020-11-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_remove_mask_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='model',
            field=models.ManyToManyField(blank=True, db_table='added', to='Main.Model'),
        ),
    ]
